
document.getElementById("square1");
document.getElementById("square2");
document.getElementById("square3");
document.getElementById("square4");
document.getElementById("square5");
document.getElementById("square6");
document.getElementById("square7");
document.getElementById("square8");
document.getElementById("square9");
document.getElementById("square10");
document.getElementById("square11");
document.getElementById("square12");
document.getElementById("square13");
document.getElementById("square14");
document.getElementById("square15");

let square1 = document.getElementById("square1");
let square2 = document.getElementById("square2");
let square3 = document.getElementById("square3");
let square4 = document.getElementById("square4");
let square5 = document.getElementById("square5");
let square6 = document.getElementById("square6");
let square7 = document.getElementById("square7");
let square8 = document.getElementById("square8");
let square9 = document.getElementById("square9");
let square10 = document.getElementById("square10");
let square11= document.getElementById("square11");
let square12 = document.getElementById("square12");
let square13 = document.getElementById("square13");
let square14 = document.getElementById("square14");
let square15 = document.getElementById("square15");

let colors = ["#F50F0F", "#FBE317","#0C7FBF","#F3F3F3","#000000", "#F3F3F3"];


square1.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square2.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square3.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square4.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square5.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square6.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square7.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square8.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square9.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square10.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square11.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square12.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square13.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square14.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];
square15.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];

square1.style.width = Math.random() * 300 +"px";
square1.style.height = Math.random() * 300 + "px";
square2.style.width = Math.random() * 300 +"px";
square2.style.height = Math.random() * 300 + "px";
square3.style.width = Math.random() * 300 +"px";
square3.style.height = Math.random() * 300 + "px";
square4.style.width = Math.random() * 300 +"px";
square4.style.height = Math.random() * 300 + "px";
square5.style.width = Math.random() * 300 +"px";
square5.style.height = Math.random() * 300 + "px";
square6.style.width = Math.random() * 300 +"px";
square6.style.height = Math.random() * 300 + "px";
square7.style.width = Math.random() * 300 +"px";
square7.style.height = Math.random() * 300 + "px";
square8.style.width = Math.random() * 300 +"px";
square8.style.height = Math.random() * 300 + "px";
square9.style.width = Math.random() * 300 +"px";
square9.style.height = Math.random() * 300 + "px";
square10.style.width = Math.random() * 300 +"px";
square10.style.height = Math.random() * 300 + "px";
square11.style.width = Math.random() * 300 +"px";
square11.style.height = Math.random() * 300 + "px";
square12.style.width = Math.random() * 300 +"px";
square12.style.height = Math.random() * 300 + "px";
square13.style.width = Math.random() * 300 +"px";
square13.style.height = Math.random() * 300 + "px";
square14.style.width = Math.random() * 300 +"px";
square14.style.height = Math.random() * 300 + "px";
square15.style.width = Math.random() * 300 +"px";
square15.style.height = Math.random() * 300 + "px";
square16.style.width = Math.random() * 300 +"px";
square16.style.height = Math.random() * 300 + "px";
square17.style.width = Math.random() * 300 +"px";
square17.style.height = Math.random() * 300 + "px";
square18.style.width = Math.random() * 300 +"px";
square18.style.height = Math.random() * 300 + "px";
square19.style.width = Math.random() * 300 +"px";
square19.style.height = Math.random() * 300 + "px";
square20.style.width = Math.random() * 300 +"px";
square20.style.height = Math.random() * 300 + "px";